/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualKeyboard: typeof import('./../src/components/VirtualKeyboard.vue')['default']
    YouCarousel: typeof import('./../src/components/YouCarousel.vue')['default']
    YouDialog: typeof import('./../src/components/YouDialog.vue')['default']
    YouDiscuss: typeof import('./../src/components/YouDiscuss.vue')['default']
    YouDrawer: typeof import('./../src/components/YouDrawer.vue')['default']
    YouDropdown: typeof import('./../src/components/YouDropdown.vue')['default']
    YouEditor: typeof import('./../src/components/YouEditor.vue')['default']
    YouFollow: typeof import('./../src/components/YouFollow.vue')['default']
    YouGuide: typeof import('./../src/components/YouGuide.vue')['default']
    YouIcon: typeof import('./../src/components/YouIcon.vue')['default']
    YouImage: typeof import('./../src/components/YouImage.vue')['default']
    YouKeyboard: typeof import('./../src/components/YouKeyboard.vue')['default']
    YouLoading: typeof import('./../src/components/YouLoading.vue')['default']
    YouMaterial: typeof import('./../src/components/YouMaterial.vue')['default']
    YouMessage: typeof import('./../src/components/YouMessage.vue')['default']
    YouPayment: typeof import('./../src/components/YouPayment.vue')['default']
    YouProfile: typeof import('./../src/components/YouProfile.vue')['default']
    YouPrompt: typeof import('./../src/components/YouPrompt.vue')['default']
    YouRich: typeof import('./../src/components/YouRich.vue')['default']
    YouSearch: typeof import('./../src/components/YouSearch.vue')['default']
    YouSetup: typeof import('./../src/components/YouSetup.vue')['default']
    YouSvg: typeof import('./../src/components/YouSvg.vue')['default']
    YouTag: typeof import('./../src/components/YouTag.vue')['default']
    YouWatch: typeof import('./../src/components/YouWatch.vue')['default']
  }
}
