/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YouDiscuss: typeof import('./../src/components/YouDiscuss.vue')['default']
    YouPayment: typeof import('./../src/components/YouPayment.vue')['default']
    YouSearch: typeof import('./../src/components/YouSearch.vue')['default']
    YouWatch: typeof import('./../src/components/YouWatch.vue')['default']
  }
}
